syntax on

packadd minpac
call minpac#init()

call minpac#add('tpope/vim-unimpaired')

" Just for VIM, not NEOVIM
call minpac#add('tpope/vim-dispatch')

call minpac#add('tpope/vim-projectionist')
call minpac#add('tpope/vim-scriptease', {'type': 'opt'})

call minpac#add('junegunn/fzf')
call minpac#add('junegunn/fzf.vim')

command! PackUpdate call minpac#update()
command! PackClean call minpac#clean()


" FZF

nnoremap <C-p> :<C-u>FZF<CR>
